name: wireless_calling_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  awesome_notifications: ^0.10.1
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  http: ^1.2.2
  # icons_launcher removed (not referenced in code)
  # intl removed (not referenced in code)
  provider: ^6.1.5+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
